services:
  dev:
    environment:
      DISPLAY: ${DISPLAY:?Run Docker Compose from an X11-forwarded shell}
      XAUTHORITY: /tmp/.docker.xauth
      QT_X11_NO_MITSHM: "1"

    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${XAUTHORITY:-${HOME}/.Xauthority}
        target: /tmp/.docker.xauth
        read_only: true
        bind:
          create_host_path: false
