services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO:-jazzy}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}

    image: quattro_ws:jazzy-dev

    network_mode: host
    ipc: host

    working_dir: /ws

    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      ROS_AUTOMATIC_DISCOVERY_RANGE: SUBNET
      PYTHONUNBUFFERED: "1"

    volumes:
      - .:/ws

    stdin_open: true
    tty: true

    command: bash
