controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: false
    hardware_components_initial_state:
      inactive: [QuattroSystem]
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    mit_trajectory_controller:
      type: quattro_controllers/MitTrajectoryController

mit_trajectory_controller:
  ros__parameters:
    joints:
      - front_left_hip_joint
      - front_left_upper_leg_joint
      - front_left_lower_leg_joint
      - front_right_hip_joint
      - front_right_upper_leg_joint
      - front_right_lower_leg_joint
      - back_left_hip_joint
      - back_left_upper_leg_joint
      - back_left_lower_leg_joint
      - back_right_hip_joint
      - back_right_upper_leg_joint
      - back_right_lower_leg_joint
    kp: [60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0]
    kd: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
    command_timeout: 0.5
